version: '3.8'
name: mimicare

services:
  mimicare-db:
    image: ${IMAGE_REGISTRY:-docker.io/}pgvector/pgvector:pg16
    pull_policy: ${PULL_POLICY:-missing}
    container_name: mimicare-db
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
      POSTGRES_DB: ${POSTGRES_DB:-mimicare}
    volumes:
      - mimicare_db_data:/var/lib/postgresql/data
      - ./init-scripts/init-pgvector.sql:/docker-entrypoint-initdb.d/init-pgvector.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres}']
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s
    networks:
      - mimicare_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

volumes:
  mimicare_db_data:
    driver: local

networks:
  mimicare_network:
    driver: bridge
