version: '3.8'
name: mimicare

services:
  localstack:
    image: ${IMAGE_REGISTRY:-docker.io/}localstack/localstack:latest
    pull_policy: ${PULL_POLICY:-missing}
    container_name: mimicare-localstack
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    environment:
      - SERVICES=s3,dynamodb,ses,sqs,lambda
      - DEFAULT_REGION=ap-south-1
      - DEBUG=1
      - PERSISTENCE=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - GATEWAY_LISTEN=0.0.0.0:4566
      - DYNAMODB_SHARED_DB=true
      - EAGER_SERVICE_LOADING=1
    volumes:
      - localstack-data:/var/lib/localstack
      - ./docker/init-scripts:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mimicare_network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  localstack-data:
    driver: local

networks:
  mimicare_network:
    driver: bridge
