version: '3.8'
name: mimicare

services:
  redis:
    image: ${IMAGE_REGISTRY:-docker.io/library/}redis:8-alpine
    pull_policy: ${PULL_POLICY:-missing}
    container_name: mimicare-redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass mimicare123
    volumes:
      - redis-data:/data
    networks:
      - mimicare_network
    healthcheck:
      test: ['CMD', 'redis-cli', '-a mimicare123', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
    driver: local

networks:
  mimicare_network:
    driver: bridge
